### ISSUE TITLE
Async Minion does not use keycloak privateUrl 

### ISSUE THREAD

**Issue by hguerrero** [microcks/microcks-ansible-operator#27]
When deploying keycloak with privateURL in the MicrocksInstall CR, the Async minion deployment stills try to use the public url (not accessible) to connect.

**Comment by lbroudoux** [comment]
Since we separate Keycloak Frontend URL from Backend URL (see microcks/microcks#119) we not have modified the behaviour of the `async-minion` component. It is still requests Microcks `/keycloak/config` endpoint to retrieve Keycloak Public URL.  On some setups (Kind clusters or clusters using NodePort exposition) this URL may not be resolvable from outside. So we need to propagate this separation to `async-minion` component first.

**Comment by lbroudoux** [comment]
Fix microcks/microcks#331 then update the Operator

**Comment by lbroudoux** [comment]
Now fixed with `quay.io/microcks/microcks-ansible-operator:latest` container image containing the fix.

**Comment by hguerrero** [comment]
Do you have a snippet of the CR config for this new option?
